### ISSUE TITLE
Move config info retrieval into helpers

### ISSUE THREAD

**Issue by mjgardner** [szabgab/course-management#1]
I think we should take @jberger's advice from our first YouTube session and move our config retrieval into a set of helper functions. The config file is basically our data model, and the templates know too much about how it's structured -- that's not good design. We should instead have a helper function for listing the courses, another for listing the users in a course, another for the exercises, etc.. This will decouple our views (templates) from our model, and make our templates easier to write (important if you're handing them off to designers) and not have to rewrite them even if we eventually replace the static config with another storage option (like a database).

We can discuss more in our next session.

**Comment by szabgab** [comment]
done already
